name = "AoC"
license = "MIT"
licenselink = "https://github.com/clj/aoc-2018/tree/master/www/themes/aoc/LICENSE"
description = "Advent of Code inspired theme"
homepage = "https://clj.github.io/aoc-2018/"
tags = ["simple"]
features = []
min_version = "0.41"

[author]
  name = "Christian Lyder Jacobsen"
  homepage = "https://clj.github.io/aoc-2018/"
